// <auto-generated />
using System;
using GestionEleves.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEleves.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231112095350_mig")]
    partial class mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEleves.Models.Etablissement", b =>
                {
                    b.Property<int>("EtablissementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtablissementId"));

                    b.Property<string>("EtablissementName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtablissementId");

                    b.ToTable("Etablissements");
                });

            modelBuilder.Entity("GestionEleves.Models.Etudient", b =>
                {
                    b.Property<int>("EtudientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtudientID"));

                    b.Property<int>("EtablissementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EtudientBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtudientFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtudientLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtudientID");

                    b.HasIndex("EtablissementId");

                    b.ToTable("Etudients");
                });

            modelBuilder.Entity("GestionEleves.Models.Etudient", b =>
                {
                    b.HasOne("GestionEleves.Models.Etablissement", "Etablissement")
                        .WithMany()
                        .HasForeignKey("EtablissementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etablissement");
                });
#pragma warning restore 612, 618
        }
    }
}
